name: Libraries publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.5

      - name: Restore nuget packages
        run: dotnet restore FinStatCSharpApi.sln

      - name: Build
        shell: bash
        run: |
          # Build everything
          dotnet build ./Tester/SK/ApiDistraintTester/ApiDistraintTester.csproj  -c Release -o "FinStatAPINETClient"
          dotnet build ./Tester/SK/ApiDailyDiffTester/ApiDailyDiffTester.csproj  -c Release -o "FinStatAPINETClient"
          dotnet build ./Tester/SK/ApiMonitoringTester/ApiMonitoringTester.csproj  -c Release -o "FinStatAPINETClient"
          dotnet build ./Tester/SK/ApiTester/ApiTester.csproj  -c Release -o "FinStatAPINETClient"

          dotnet build ./Tester/CZ/ApiMonitoringTester/ApiMonitoringTester.csproj  -c Release -o "FinStatCZAPINETClient"
          dotnet build ./Tester/CZ/ApiCzTester/ApiCzTester.csproj  -c Release -o "FinStatCZAPINETClient"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "FinStatAPINETClient.zip" "./FinStatAPINETClient/*"
            7z a -tzip "FinStatCZAPINETClient.zip" "./FinStatCZAPINETClient/*"
          else
            tar czvf "FinStatAPINETClient.tar.gz" "FinStatAPINETClient"
            tar czvf "FinStatCZAPINETClient.tar.gz" "FinStatCZAPINETClient"
          fi

          # Delete output directory
          rm -r "FinStatAPINETClient"
          rm -r "FinStatCZAPINETClient"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
